name: roobo_base
description: roobo基础组件库 提供开发中各种基础组件 详见api
version: 2.1.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  package_info: ^2.0.2
  provider: ^6.0.2    #跨组件状态共享
  flutter_easyloading: ^3.0.3 #toast loading库

  roobo_net:
    git:
      url: git@git.365jiating.com:app_base_project/roobo_net.git
      ref: 2.0.0

  roobo_theme:
    git:
      url: git@git.365jiating.com:app_base_project/roobo_theme.git
      ref: 2.0.1

  roobo_logger:
    git:
      url: git@git.365jiating.com:app_base_project/roobo_logger.git
      ref: 2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
 assets:
   - res/img/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
